### ISSUE TITLE
NFT can be bought multiple time

### ISSUE THREAD

**Issue by RedWilly** [LinuxKunaL/gigatrade-NFTs-Marketplace#3]
so i started out testing the website and i notice the marketplace allow for an nft id to be bought multiple time but the same user and the frontend does not take into account for that 

https://sepolia.etherscan.io/token/0x9b27f429a6ced75d86ea6fd8fc2db10815f636c7?a=0xcd44bcabc2fdc0a4a7091d9206941f0ab1d50f9e

well i think the first transcation was from the marketplace but the second transcation i bought from by self for some reason and the marketplace allowed that. 

it should have removed the nft from marketplace, since now the marketplace does not own the nft, and once and nft is bought and not listed it shouldnt be on sale

**Comment by LinuxKunaL** [comment]
Sir , in the opensea platform we can create our own nft and sell them , when you create a nft first of all we need to create there specific collection and that collection is entire smart contract and this contract is own buy you , but in my Marketplace i implement different logic I'm creating a only one smart contract for whole platform and user can make NFT in only in that marketplace contract . 

Any further questions ?
